<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $appends = ['image_path' , 'short_description'];

    protected $fillable = ['description' , 'title' , 'phone' , 'image' , 'user_id'];

    public function user()
    {
        return $this->belongsTo(User::class , 'user_id');
    }

    public function getShortDescriptionAttribute() {
        return substr($this->description, 0, 512);
    }

    public function getImagePathAttribute()
    {
        return asset('uploads/' . $this->image) ;
    }

    protected static function boot(){
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($row){
            $row->user_id = \Auth::user()->id;
        });
    }

}
